### ISSUE TITLE
[BUG] Unable to see application name if it is too long

### ISSUE THREAD

**Issue by Nopparuj-an** [tw93/Mole#111]
## Describe the bug

Unable to see application name if it is too long.

## Steps to reproduce

1. Run command: `mo ...`
2. Select `Uninstall`

## Expected behavior

Being able to see application name, either by scrolling text, or by a hint on top or bottom of the screen.

## Debug logs

Not applicable.

## Environment

- Mole version: 1.12.1
- macOS version: 15.5 Build 24F74
- Installation method: Homebrew
- Architecture: Apple Silicon

## Additional context

<img width="938" height="665" alt="Image" src="https://github.com/user-attachments/assets/bed93b18-ebaa-40a5-9cea-572d02218805" />

**Comment by tw93** [comment]
Thank you very much for your feedback. I made a brief repair, and then you can `mo update` to upgrade to version 1.12.3 for testing. It should be fixed, and then the width was increased.

**Comment by apiep** [comment]
<img width="1792" height="1088" alt="Image" src="https://github.com/user-attachments/assets/6fc74a2d-b291-448d-b3f2-45b931ea5131" />

Still unable to see the application name.
```
Mole version 1.13.5
macOS: 26.1
Architecture: arm64
Kernel: 25.1.0
SIP: Enabled
Disk Free: 12Gi
Install: Homebrew
Shell: /opt/homebrew/bin/fish
```
