### ISSUE TITLE
[BUG] Invalid system health data format in Optimize

### ISSUE THREAD

**Issue by pnsrc** [tw93/Mole#114]
Optimize and Check

☻ Invalid system health data format
Tip: Check if jq, awk, sysctl, and df commands are available
dontfffafk@MacBook-Air-Aleksej ~ % 

<img width="593" height="397" alt="Image" src="https://github.com/user-attachments/assets/8b8408c3-4423-4939-9af4-bc9261976aa8" />

**Comment by tw93** [comment]
Hard to update to the latest version 1.12.6 and try it out; it has been fixed, and it should be a compatibility issue with some locales.

**Comment by vinicius0026** [comment]
Still seeing this on version 1.19.0, just installed from Homebrew.

```
$ mo --version

Mole version 1.19.0
macOS: 15.6.1
Architecture: arm64
Kernel: 24.6.0
SIP: Enabled
Disk Free: 114Gi
Install: Manual
Shell: /bin/zsh
```

Let me know if I can provide additional information that could help with this. Thanks.
