### ISSUE TITLE
[BUG] System Settings is corrupted after `mo optimize`

### ISSUE THREAD

**Issue by necipsagiro** [tw93/Mole#136]
## Describe the bug

After I do `mo optimize` my System Settings app looks like this:

<img width="741" height="804" alt="Image" src="https://github.com/user-attachments/assets/af9cb09f-ffae-4b9c-9285-182217c60700" />

If I restart my pc it returns back to normal. [It's mentioned that this issue is solved](https://github.com/tw93/Mole/issues/118#issuecomment-3644601876) in version `1.12.13`, I'm on `1.13.5` but still see this issue.

## Steps to reproduce

1. Run command: `mo optimize`
2. Open `System Settings`
3. See error

## Expected behavior

System Settings should work as expected

## Debug logs

Please run the command with `--debug` flag and paste the output here:

<details>
<summary>Debug output</summary>

```bash
mo optimize --debug
[DEBUG] Debug logging enabled. Session log: /Users/necipsagiroglu/.config/mole/mole_debug_session.log

Optimize and Check
⚙ System  1/8 GB RAM | 107/208 GB Disk | Uptime 0d
⚙ Active Whitelist: 4 items

➤ System optimization requires admin access (Touch ID or password)
➤ System Maintenance - Rebuild system databases & flush caches
➤ Rebuilding LaunchServices database...
✓ LaunchServices database rebuilt
➤ Clearing DNS cache...
✓ DNS cache cleared
➤ Checking Spotlight index...
✓ Spotlight index functioning
➤ Refreshing Bluetooth services...
✓ Bluetooth controller refreshed

➤ Maintenance Scripts - Rotate system logs
➤ Rotating system logs...
✓ Logs rotated

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...
[DEBUG] Finding in /Users/necipsagiroglu/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
✓ Shared file lists cleared
✓ Recent items cleared

➤ Diagnostics Cleanup - Purge old diagnostic & crash logs
➤ Clearing diagnostic & crash logs...
✓ DiagnosticReports
✓ corecaptured
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
✓ System diagnostic logs cleared

➤ Mail Downloads - Clear old mail attachments (> 30 days)
➤ Clearing old Mail attachment downloads (30+ days)...
- Only 960KB detected, skipping cleanup

➤ Swap Refresh - Reset swap files and dynamic pager
➤ Removing swapfiles and resetting dynamic pager...
✓ Swap cache rebuilt

➤ Spotlight Cache - Clear user-level Spotlight indexes
➤ Cleaning Spotlight user caches...
[DEBUG] Removing: /Users/necipsagiroglu/Library/Metadata/CoreSpotlight
  ✓ CoreSpotlight cache (97.3MB)
✓ Cleaned 1 items (97.3MB)
☻ System settings may require logout/restart to display correctly

➤ Developer Cleanup - Clear Xcode DerivedData & DeviceSupport
✓ Xcode DerivedData
✓ iOS Device support files
[DEBUG] Removing: /Users/necipsagiroglu/Library/Developer/CoreSimulator/Caches
✓ CoreSimulator caches
➤ Removing unavailable simulator runtimes...
✓ Unavailable simulators removed
✓ Developer caches cleaned

➤ Network Optimization - Flush DNS, ARP & reset mDNS
➤ Optimizing network settings...
  ✓ DNS cache flushed
  ✓ ARP cache cleared
  ✓ Network interfaces refreshed
✓ Network optimized

System Check

➤ System updates
  ☻ macOS        Update available
    update available in final step
  ✓ Mole         Up to date (unknown)

➤ System health
  ✓ Disk Space   87GB free
  ✓ Memory       78% used
  ✓ Swap Usage   0.00M
  ✓ Login Items  2 apps auto-start
    Lunar, Raycast
    Manage in System Settings → Login Items
  ✓ Cache Size   .7GB

➤ Security posture
  ✓ FileVault    Enabled
  ✓ Firewall     Enabled
  ✓ Gatekeeper   Active
  ✓ SIP          Enabled

➤ Configuration
  ✓ Rosetta 2    Installed

➤ Suggestions
  ✓ All looks good

AVAILABLE UPDATES
  • macOS system

Tip: Open System Settings to update macOS


======================================================================
Optimization and Check Complete
Optimizations: 9 applied, 0 manual checks
Caches refreshed; services restarted; system tuned
Updates & security reviewed across system
Mac should feel faster and more responsive
======================================================================
Debug session log saved to: /Users/necipsagiroglu/.config/mole/mole_debug_session.log
```

`/Users/necipsagiroglu/.config/mole/mole_debug_session.log`:
```
----------------------------------------------------------------------
Mole Debug Session - 2025-12-17 15:07:30
----------------------------------------------------------------------
User: necipsagiroglu
Hostname: Necips-MacBook-Air.local
Architecture: arm64
Kernel: 24.3.0
macOS: 15.3.2 (24D81)
Shell: /bin/zsh (xterm-256color)
Sudo Access: Required
----------------------------------------------------------------------
[2025-12-17 15:07:39] DEBUG: Finding in /Users/necipsagiroglu/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
[2025-12-17 15:07:39] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[2025-12-17 15:07:39] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
[2025-12-17 15:07:39] DEBUG: Removing: /Users/necipsagiroglu/Library/Metadata/CoreSpotlight
[2025-12-17 15:07:39] DEBUG: Removing: /Users/necipsagiroglu/Library/Developer/CoreSimulator/Caches
```

</details>

## Environment

Please run `mo update` to ensure you are on the latest version, then paste the output of `mo --version` below:

```text
✓ Already on latest version (1.13.5)

mo --version

Mole version 1.13.5
macOS: 15.3.2
Architecture: arm64
Kernel: 24.3.0
SIP: Enabled
Disk Free: 81Gi
Install: Homebrew
Shell: /bin/zsh
```

**Comment by tw93** [comment]
Thank you very much for your feedback, I have strengthened this area. In fact, you just need to restart your computer. However, I have added a restriction in the latest version, not to clear the system cache files, and then you can try to `mo update` to 1.13.6 with mo update to see if the issue still occurs, it should be fixed.

**Comment by necipsagiro** [comment]
Thank you for the fast response, I tried the new version and issue is not completely gone. Now the items in the sidebar is there but:
  - I can't go into any menu, only Spotlight and General.
  - General menu is empty

Here is the video:

https://github.com/user-attachments/assets/b8823c1f-5199-4286-b28e-c319b6df7922

**Comment by tw93** [comment]
Hi there, @necipsagiro 

Thank you for reporting this and providing the feedback. I have just released version 1.13.7 which specifically addresses this System Settings corruption issue.

Please follow these steps to verify the fix:

Restart your Mac: This will restore the current corrupted System Settings UI to its normal state.
Update Mole: Run mo update to upgrade to the latest version 1.13.7.
Run again: Execute your optimization or cleanup command again to verify that the issue no longer occurs.


Technical Explanation: The issue was caused by the accidental cleanup of certain sandboxed containers and XPC service caches (specifically com.apple.systempreferences.cache) that modern macOS (Sonoma/Sequoia) relies on to render the System Settings interface. This resulted in the "blank panel" behavior you experienced.

I have implemented more comprehensive protection across the codebase to ensure that all System Settings, Preferences, and Control Center components are explicitly bypassed during both mo optimize and mo clean operations.

Please let us know if you encounter any further issues!

Best regards.

**Comment by tw93** [comment]
https://github.com/tw93/Mole/issues/124

**Comment by minhdat97** [comment]
The issue still occurs in version 1.13.7. After excute optimize or clean command, the System Settings UI still corrupt.

**Comment by tw93** [comment]
Hi @minhdat97 @necipsagiro @

I've just released **v1.13.8** which fixes this System Settings corruption issue.

**Root cause**: The cleanup accidentally removed critical system caches   (`com.apple.systempreferences.cache`, etc.) that macOS Sonoma/Sequoia  needs to render the System Settings UI.

**To fix**:
1. **Restart your Mac** (to restore System Settings UI)
2. Run `mo update` to upgrade to v1.13.8
3. The issue should no longer occur

The new version adds comprehensive protection for all System Settings, Control Center, and related system caches.

Please let me know if you still encounter any issues after updating!

**Comment by minhdat97** [comment]
I try version 1.13.8 but issue still occurs.

**Comment by tw93** [comment]
@minhdat97 Have you restarted your computer? Would it be convenient to look at the detailed output of mo optimize --debug?

**Comment by minhdat97** [comment]
I restarted my mac before run optimize command.

**Here is log when excute optimize command:**
```
Optimize and Check
⚙ System  3/24 GB RAM | 378/926 GB Disk | Uptime 0d
⚙ Active Whitelist: 5 items

➤ System optimization requires admin access (Touch ID or password)
➤ System Maintenance - Rebuild system databases & flush caches
➤ Rebuilding LaunchServices database...
✓ LaunchServices database rebuilt
➤ Clearing DNS cache...
✓ DNS cache cleared
➤ Checking Spotlight index...
✓ Spotlight index functioning
➤ Refreshing Bluetooth services...
✓ Bluetooth controller refreshed

➤ Maintenance Scripts - Rotate system logs
➤ Rotating system logs...
✓ Logs rotated

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...
[DEBUG] Finding in /Users/***/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
✓ Shared file lists cleared
✓ Recent items cleared

➤ Diagnostics Cleanup - Purge old diagnostic & crash logs
➤ Clearing diagnostic & crash logs...
[DEBUG] Removing: /Users/***/Library/Logs/DiagnosticReports
✓ DiagnosticReports
✓ corecaptured
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
✓ System diagnostic logs cleared

➤ Mail Downloads - Clear old mail attachments (> 30 days)
➤ Clearing old Mail attachment downloads (30+ days)...
- Only 0B detected, skipping cleanup

➤ Swap Refresh - Reset swap files and dynamic pager
➤ Removing swapfiles and resetting dynamic pager...
✓ Swap cache rebuilt

➤ Developer Cleanup - Clear Xcode DerivedData & DeviceSupport
✓ Xcode DerivedData
✓ iOS Device support files
✓ CoreSimulator caches
➤ Removing unavailable simulator runtimes...
✓ Unavailable simulators removed
✓ Developer caches cleaned

➤ Network Optimization - Flush DNS, ARP & reset mDNS
➤ Optimizing network settings...
  ✓ DNS cache flushed
  ✓ ARP cache cleared
  ✓ Network interfaces refreshed
✓ Network optimized

System Check

➤ System updates
  ✓ Mole         Up to date (unknown)

➤ System health
  ✓ Disk Space   569GB free
  ✓ Memory       53% used
  ✓ Swap Usage   0.00M
  ✓ Login Items  5 apps auto-start
    Zalo, Raycast, FigmaAgent, PHTV, CleanShot X
    Manage in System Settings → Login Items
  ✓ Cache Size   .6GB

➤ Security posture
  ✓ FileVault    Enabled
  ✓ Firewall     Enabled
  ✓ Gatekeeper   Active
  ✓ SIP          Enabled

➤ Configuration
  ✓ Rosetta 2    Installed

➤ Suggestions
  ✓ All looks good
```


**Here is file mole_debug_session.log:**

```
----------------------------------------------------------------------
Mole Debug Session - 2025-12-18 11:02:25
----------------------------------------------------------------------
User: dattm
Hostname: *****
Architecture: arm64
Kernel: 24.6.0
macOS: 15.7.3 (24G419)
Shell: /bin/zsh (xterm-256color)
Sudo Access: Required
----------------------------------------------------------------------
[2025-12-18 11:02:30] DEBUG: Finding in /Users/***/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
[2025-12-18 11:02:30] DEBUG: Removing: /Users/***/Library/Logs/DiagnosticReports
[2025-12-18 11:02:30] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[2025-12-18 11:02:30] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
```

**Comment by tw93** [comment]
@minhdat97 @necipsagiro

Thank you for the detailed reports! I've identified and fixed the issue.

The mo clean command was removing System Settings savedState files. The protection logic missed com.apple.Settings (used in macOS Sequoia), causing the UI corruption.

Please upgrade to v1.13.9:  mo update

After updating:
1. Restart your Mac to restore System Settings
2. Run mo clean or mo optimize - the issue should be resolved

The fix adds explicit protection for all System Settings variants including com.apple.Settings, com.apple.SystemSettings, and com.apple.systempreferences.

Please let me know if the issue persists after upgrading.

**Comment by minhdat97** [comment]
Version 1.13.9 not work.

```
Mole version 1.13.9
macOS: 15.7.3
Architecture: arm64
Kernel: 24.6.0
SIP: Enabled
Disk Free: 526Gi
Install: Homebrew
Shell: /bin/zsh
```

**Here is log when excute optimize command:**
```
Optimize and Check
⚙ System  3/24 GB RAM | 388/926 GB Disk | Uptime 0d
⚙ Active Whitelist: 5 items

➤ System optimization requires admin access (Touch ID or password)
➤ System Maintenance - Rebuild system databases & flush caches
➤ Rebuilding LaunchServices database...
✓ LaunchServices database rebuilt
➤ Clearing DNS cache...
✓ DNS cache cleared
➤ Checking Spotlight index...
✓ Spotlight index functioning
➤ Refreshing Bluetooth services...
✓ Bluetooth controller refreshed

➤ Maintenance Scripts - Rotate system logs
➤ Rotating system logs...
✓ Logs rotated

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...
[DEBUG] Finding in /Users/***/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
✓ Shared file lists cleared
✓ Recent items cleared

➤ Diagnostics Cleanup - Purge old diagnostic & crash logs
➤ Clearing diagnostic & crash logs...
[DEBUG] Removing: /Users/***/Library/Logs/DiagnosticReports
✓ DiagnosticReports
✓ corecaptured
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[DEBUG] Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
✓ System diagnostic logs cleared

➤ Mail Downloads - Clear old mail attachments (> 30 days)
➤ Clearing old Mail attachment downloads (30+ days)...
- Only 0B detected, skipping cleanup

➤ Swap Refresh - Reset swap files and dynamic pager
➤ Removing swapfiles and resetting dynamic pager...
✓ Swap cache rebuilt

➤ Developer Cleanup - Clear Xcode DerivedData & DeviceSupport
[DEBUG] Removing: /Users/***/Library/Developer/Xcode/DerivedData
✓ Xcode DerivedData (6.81GB)
✓ iOS Device support files
[DEBUG] Removing: /Users/***/Library/Developer/CoreSimulator/Caches
✓ CoreSimulator caches
➤ Removing unavailable simulator runtimes...
✓ Unavailable simulators removed
✓ Developer caches cleaned

➤ Network Optimization - Flush DNS, ARP & reset mDNS
➤ Optimizing network settings...
  ✓ DNS cache flushed
  ✓ ARP cache cleared
  ✓ Network interfaces refreshed
✓ Network optimized

System Check

➤ System updates
  ✓ Mole         Up to date (unknown)

➤ System health
  ✓ Disk Space   566GB free
  ✓ Memory       56% used
  ✓ Swap Usage   0.00M
  ✓ Login Items  5 apps auto-start
    Zalo, Raycast, FigmaAgent, PHTV, CleanShot X
    Manage in System Settings → Login Items
  ✓ Cache Size   3.1GB

➤ Security posture
  ✓ FileVault    Enabled
  ✓ Firewall     Enabled
  ✓ Gatekeeper   Active
  ✓ SIP          Enabled

➤ Configuration
  ✓ Rosetta 2    Installed

➤ Suggestions
  ✓ All looks good


======================================================================
Optimization and Check Complete
Optimizations: 8 applied, 0 manual checks
Caches refreshed; services restarted; system tuned
Updates & security reviewed across system
Mac should feel faster and more responsive
======================================================================
Debug session log saved to: /Users/***/.config/mole/mole_debug_session.log
```

**Here is mole_debug_session.log:**

```
----------------------------------------------------------------------
Mole Debug Session - 2025-12-18 14:29:25
----------------------------------------------------------------------
User: dattm
Hostname: ***
Architecture: arm64
Kernel: 24.6.0
macOS: 15.7.3 (24G419)
Shell: /bin/zsh (xterm-256color)
Sudo Access: Required
----------------------------------------------------------------------
[2025-12-18 14:29:30] DEBUG: Finding in /Users/***/Library/Application Support/com.apple.sharedfilelist: *.sfl2 (age: 0d, type: f)
[2025-12-18 14:29:30] DEBUG: Removing: /Users/***/Library/Logs/DiagnosticReports
[2025-12-18 14:29:30] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.crash (age: 0d, type: f)
[2025-12-18 14:29:30] DEBUG: Finding (sudo) in /Library/Logs/DiagnosticReports: *.panic (age: 0d, type: f)
[2025-12-18 14:29:31] DEBUG: Removing: /Users/***/Library/Developer/Xcode/DerivedData
[2025-12-18 14:29:36] DEBUG: Removing: /Users/***/Library/Developer/CoreSimulator/Caches
```

**Comment by tw93** [comment]
@minhdat97 Not executing the mo command, after the restart, isn't it good if the settings have been restored? Then, after executing mo optimize, isn't it not working anymore?

**Comment by minhdat97** [comment]
> [@minhdat97](https://github.com/minhdat97) Not executing the mo command, after the restart, isn't it good if the settings have been restored? Then, after executing mo optimize, isn't it not working anymore?

After restart my mac, the setting UI restore. Then, i run command "mo optimize --debug". When optimize done i open setting again, the setting UI corrupt.

**Comment by tw93** [comment]
@minhdat97 Please upgrade to the latest 1.13.10 and continue to test in the same way. This time, I should find the issue, thank you for your trouble.

**Comment by minhdat97** [comment]
> [@minhdat97](https://github.com/minhdat97) Please upgrade to the latest 1.13.10 and continue to test in the same way. This time, I should find the issue, thank you for your trouble.

Version 1.13.10 still not work

**Comment by tw93** [comment]
@minhdat97 I continue to optimize, continue to delve deeper into potential issues, and still need to trouble you to update to version 1.13.12 and try again to see if there are any problems.

**Comment by necipsagiro** [comment]
@tw93 I updated to version `1.13.12` and tested, still the same problem as https://github.com/tw93/Mole/issues/136#issuecomment-3665575030

**Comment by hazarguney** [comment]
I installed the version `1.13.13` and it also caused the same issue.

**Comment by qemotion** [comment]
I installed the 1.13.13 too and got same problem with mo optimize. Even after restarting, happened again.

(macOS 13.5.1)

🙀 Do you know how to deactivate the mole in status screen ?

**Comment by tw93** [comment]
@hazarguney @minhdat97 @qemotion @necipsagiro 
I am truly sorry to have kept everyone waiting, I have completely removed this optimization action, please continue to upgrade to 1.14.0 and see if it is fixed.

**Comment by necipsagiro** [comment]
@tw93 It works now! Thanks, can you explain a little why it was happening?

**Comment by tw93** [comment]
@necipsagiro This issue is indeed very complex, I feel it's a problem with the macOS system cache. Initially, I wanted to simply filter out any uncleaned caches here, but due to the large number of files, there were always some omissions. Later, I learned that the benefits of cleaning the system configuration cache here are not as great as I thought, so I completely removed this optimization project.
