### ISSUE TITLE
[BUG]  mole purge error in project.sh ; unbound variable

### ISSUE THREAD

**Issue by auntchilada** [tw93/Mole#141]
## Describe the bug

:: mole purge error in project.sh ; unbound variable

\# mo purge

Purge Project Artifacts
/opt/homebrew/Cellar/mole/1.13.13/libexec/bin/../lib/clean/project.sh: line 503: scan_pids[@]: unbound variable
| Scanning projects...^C

$ sw_vers

ProductName:		macOS
ProductVersion:		15.7.2
BuildVersion:		24G325

$ brew config

HOMEBREW_VERSION: 5.0.6-53-g0ff3a70
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ff3a7044d21f6815de12d4200a739c38590d537
Last commit: 25 hours ago
Branch: main
Core tap JSON: 19 Dec 00:32 UTC
Core cask tap JSON: 19 Dec 00:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 15
HOMEBREW_DISPLAY: :0.0
HOMEBREW_DOWNLOAD_CONCURRENCY: 16
HOMEBREW_EDITOR: bbedit
HOMEBREW_EVAL_ALL: set
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 17.0.0 build 1700
Git: 2.52.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.7.2-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: 26.1.1
Metal Toolchain: N/A
Rosetta 2: false

:: mole purge error and hung process

 root@h::~/Documents/work/rj ; Fri 19 Dec 1:14:02p  :::  

\# mole purge

Purge Project Artifacts
/opt/homebrew/Cellar/mole/1.13.13/libexec/bin/../lib/clean/project.sh: line 503: scan_pids[@]: unbound variable
| Scanning projects...^C

 root@h::~/Documents/work/rj ; Fri 19 Dec 1:14:07p  :1:1:  

/ Scanning projects...^C

...

:: had to kill -hup processID

## Steps to reproduce

1. Run command: `mo ...`

as root, run:

mole purge

3. ...

/opt/homebrew/Cellar/mole/1.13.13/libexec/bin/../lib/clean/project.sh: line 503: scan_pids[@]: unbound variable

## Expected behavior

:: whatever a successful run of mole purge looks like

## Debug logs

Please run the command with `--debug` flag and paste the output here:

:: nothing useful

## Environment

Please run `mo update` to ensure you are on the latest version, then paste the output of `mo --version` below:

```text
.# mo --version


Mole version 1.13.13
macOS: 15.7.2
Architecture: arm64
Kernel: 24.6.0
SIP: Enabled
Disk Free: 103Gi
Install: Manual
Shell: /opt/homebrew/bin/bash
```

## Additional context

Add any other context about the problem here, such as screenshots or related issues.

**Comment by tw93** [comment]
@auntchilada Thank you for your feedback, please `mo update` to version 1.14.0, compatibility has been fixed, and you can check if it's okay.

**Comment by bunnycake21** [comment]
hi, it seems like this problem still exists. i have run `mo update` and have verified that it is version 1.14.2, but `mo purge` does not work.

**Comment by markburgessstl** [comment]
Agreed, unfortunately the bug is still there with the latest release

**Comment by tw93** [comment]
@auntchilada @markburgessstl @bunnycake21 
Thank you very much for your feedback. I continued to check the code, and this fix resolves the fundamental issue of accessing an empty array under set -u mode, which can be upgraded to 1.14.3 using mo update.

**Comment by bunnycake21** [comment]
this seems to have been fixed. thank you!
