### ISSUE TITLE
`mo optimize` crashed - Recent Items

### ISSUE THREAD

**Issue by lonlydwolf** [tw93/Mole#61]
I ran `mo optimize` and it crashed when it reached "Recent Items"

```
mo optimize

Optimize Your Mac

System: 1/8 GB RAM | 99/228 GB Disk (44%) | Uptime 20411d

➤ System Maintenance - Rebuild system databases & flush caches
➤ Rebuilding LaunchServices database...
✓ LaunchServices database rebuilt
➤ Flushing DNS cache...
✓ DNS cache flushed
➤ Purging memory cache...
✓ Memory cache purged
➤ Rebuilding font cache...
✓ Font cache rebuilt
➤ Rebuilding Spotlight index...
✓ Spotlight index rebuilt

➤ Maintenance Scripts - Run daily/weekly/monthly scripts & rotate logs
➤ Running macOS periodic scripts...
➤ Rotating system logs...
✓ Log rotation complete

➤ Bluetooth & Wi-Fi Refresh - Reset wireless preference caches
➤ Resetting Bluetooth preferences...
  ✓ Bluetooth caches refreshed
➤ Resetting Wi-Fi configuration...
  ✓ Wi-Fi preferences reset
  ✓ Wireless services refreshed

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...

```
 
Tried it a few more times, and even after a system restart, got the same output.

**Comment by tw93** [comment]
Thanks for reporting this issue!

I've identified and fixed the crash in the Recent Items cleanup step. The problem was caused by:

1. **Incorrect use of `find -print -delete`**: The `-delete` option removes files before `-print` can output them, causing the pipe to fail
2. **Unsafe `defaults delete` call**: The command could fail if the key doesn't exist

## Fixed in latest commit

The changes made:
- Split the file counting and deletion into two separate steps for reliability
- Added a check before attempting to delete the NSGlobalDomain key

You can update to the latest version with:
```bash
mo update
```

Or manually pull the latest changes and reinstall:
```bash
cd /path/to/Mole
git pull
./install.sh
```

The `mo optimize` command should now complete the Recent Items step without crashing. Please let me know if you encounter any further issues!

**Comment by tw93** [comment]
Thank you very much for your feedback. It was due to a place I didn't consider well, which has been fixed. Please use the latest 1.9.18 version and update with `mo update`.

If there are any questions, you can reopen this issue.

**Comment by lonlydwolf** [comment]
Thanks for your prompt reply and following up with the issue, but unfortunately, the issue remains in the latest version:

```zsh
~
➜ mo update
✓ Already on latest version (1.10.0)

~
➜ mo optimize
Optimize Your Mac

➤ System optimizations require admin access
➤ Password:
⚙ System: 1/8 GB RAM | 103/228 GB Disk (45%) | Uptime 20413d

➤ System Maintenance - Rebuild system databases & flush caches
➤ Rebuilding LaunchServices database...
✓ LaunchServices database rebuilt
➤ Flushing DNS cache...
✓ DNS cache flushed
➤ Purging memory cache...
✓ Memory cache purged
➤ Rebuilding font cache...
✓ Font cache rebuilt
➤ Rebuilding Spotlight index...
✓ Spotlight index rebuilt

➤ Maintenance Scripts - Run daily/weekly/monthly scripts & rotate logs
➤ Running macOS periodic scripts...
➤ Rotating system logs...
✓ Log rotation complete

➤ Bluetooth & Wi-Fi Refresh - Reset wireless preference caches
➤ Resetting Bluetooth preferences...
  ✓ Bluetooth caches refreshed
➤ Resetting Wi-Fi configuration...
  ✓ Wi-Fi preferences reset
  ✓ Wireless services refreshed

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...

~ 
✗
```

**Comment by tw93** [comment]
@lonlydwolf 
Thank you for your feedback! I found the problem.

In the Recent Items cleaning step, the error redirection method of the defaults read command will cause the script to quit unexpectedly under some system configurations.

The issue has been fixed in the latest submission. Changed &> dev/null to > dev/null 2>&1 for better compatibility.

Please update to the latest version:
```
mo update
```

If the problem persists, you can try to run this command manually to help diagnose:
```
defaults read NSGlobalDomain NSRecentDocumentsLimit
```

**Comment by waysonlau125** [comment]
(base) ➜  ~ defaults read NSGlobalDomain NSRecentDocumentsLimit
2025-11-22 13:22:44.211 defaults[58147:684354]
The domain/default pair of (kCFPreferencesAnyApplication, NSRecentDocumentsLimit) does not exist
(base) ➜  ~

**Comment by tw93** [comment]
@lonlydwolf @waysonlau125 Can the latest version be used normally?

**Comment by waysonlau125** [comment]
> [@lonlydwolf](https://github.com/lonlydwolf) [@waysonlau125](https://github.com/waysonlau125)最新版本可以正常使用吗？

➤ Bluetooth & Wi-Fi Refresh - Reset wireless preference caches
➤ Resetting Bluetooth preferences...
  ✓ Bluetooth caches refreshed
➤ Resetting Wi-Fi settings...
  ✓ Wi-Fi preferences reset
  ✓ Wireless services refreshed

➤ Recent Items - Clear recent apps/documents/servers lists
➤ Clearing recent items lists...
(base) ➜  ~ mo --version

Mole version 1.10.4

(base) ➜  ~

**Comment by tw93** [comment]
@waysonlau125 Thank you for the feedback. I continued to upgrade. It's strange. My side has always been good.

You can try mo update to 1.10.5.
